# Generated by Django 2.2 on 2019-06-20 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('FirstName', models.CharField(blank=True, help_text='First name', max_length=25)),
                ('LastName', models.CharField(blank=True, help_text='Last name', max_length=25)),
                ('FatherName', models.CharField(blank=True, help_text="Father's name", max_length=25)),
                ('MotherName', models.CharField(blank=True, help_text="Mother's name", max_length=25)),
                ('BDay', models.CharField(blank=True, help_text='Birth Day', max_length=2)),
                ('BMonth', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', help_text='Birth Month', max_length=15)),
                ('BYear', models.CharField(blank=True, help_text='Birth Year', max_length=4)),
                ('Age', models.CharField(blank=True, help_text='Age', max_length=25)),
                ('Sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Transgender')], default='male', help_text='Gender', max_length=10)),
                ('Address1', models.CharField(blank=True, help_text='Address 1', max_length=100)),
                ('Address2', models.CharField(blank=True, help_text='Address 2', max_length=100)),
                ('Address3', models.CharField(blank=True, help_text='Address 3', max_length=100)),
                ('Address4', models.CharField(blank=True, help_text='Address 4', max_length=100)),
                ('City', models.CharField(blank=True, help_text='City/Town', max_length=25)),
                ('Pincode', models.CharField(blank=True, help_text='Pincode', max_length=6)),
                ('YourPhone', models.CharField(blank=True, help_text='Your Phone Number', max_length=10)),
                ('IsWA', models.BooleanField(default=True)),
                ('FatherPhone', models.CharField(blank=True, help_text="Father's Phone Number", max_length=10)),
                ('MotherPhone', models.CharField(blank=True, help_text="Mother's Phone Number", max_length=10)),
                ('State', models.CharField(choices=[('KA', 'Karnataka'), ('AP', 'Andhra Pradesh'), ('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('UP', 'Uttar Pradesh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('RJ', 'Rajasthan'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('TG', 'Telangana'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chattisgarh'), ('HR', 'Haryana'), ('JH', 'Jharkhand'), ('MP', 'Madhya Pradesh'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Orissa'), ('PB', 'Punjab'), ('SK', 'Sikkim'), ('TR', 'Tripura'), ('UA', 'Uttarakhand'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Pondicherry')], default='TN', help_text='State/Territory', max_length=15)),
                ('Country', models.CharField(default='India', help_text='Country', max_length=30)),
                ('Aadhar', models.CharField(blank=True, help_text='Aadhar Number', max_length=16)),
                ('License', models.CharField(blank=True, help_text='License Number', max_length=25)),
                ('Passport', models.CharField(blank=True, help_text='Passport Number', max_length=25)),
                ('VoterID', models.CharField(blank=True, help_text='VoterID Number', max_length=25)),
                ('Department', models.CharField(blank=True, choices=[('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('EEE', 'Electrical and Electronics'), ('ECE', 'Electronics and Communication'), ('CSE', 'Computer Science and Engineering'), ('OTHER', 'Others')], help_text='Department', max_length=15)),
                ('College', models.CharField(blank=True, choices=[('GCEBODI', 'Government College of Engineering, Bodinayakkanur'), ('OTHER', 'Other')], default='GCEBODI', help_text='College, City', max_length=100)),
                ('Hostage', models.CharField(blank=True, choices=[('DS', 'Day Scholar'), ('HSTL', 'Hostel'), ('PG', 'Paying Guest')], help_text='Hostage', max_length=15)),
                ('Transport', models.CharField(blank=True, choices=[('SW', 'Self Walk'), ('SV', 'Self Vehicle'), ('PT', 'Public Transport')], help_text='Medium of Transport', max_length=15)),
                ('Roll', models.CharField(blank=True, help_text='Roll Number', max_length=7)),
                ('Aureg', models.CharField(blank=True, help_text='Anna University Number', max_length=12)),
                ('Year', models.CharField(blank=True, choices=[('FY', 'First Year'), ('SY', 'Second Year'), ('TY', 'Third Year'), ('LY', 'Fourth Year')], default='FY', help_text='Year of Study', max_length=15)),
                ('Designation', models.CharField(blank=True, choices=[('STU', 'Student'), ('STF', 'Staff')], default='STU', help_text='Status', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Current Date/Time')),
                ('present', models.BooleanField(default=False, help_text='Present/Absent')),
                ('hour', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], help_text='Hour', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
