# Generated by Django 2.2 on 2019-06-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_attendance_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(choices=[('Subject1', 'Subject1'), ('Subject2', 'Subject2'), ('Subject3', 'Subject3'), ('Subject4', 'Subject4'), ('Subject5', 'Subject5')], help_text='Subject', max_length=255, null=True),
        ),
    ]
