# Generated by Django 2.2 on 2019-06-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190620_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
