# Generated by Django 2.2 on 2019-06-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
