# Generated by Django 2.2 on 2019-06-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date_of',
            new_name='date',
        ),
    ]
