# Generated by Django 2.2 on 2019-06-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190621_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancee',
            old_name='student',
            new_name='user',
        ),
    ]
