# Generated by Django 2.2 on 2019-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190621_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BloodGroup',
            field=models.CharField(blank=True, choices=[('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve'), ('O +ve', 'O +ve'), ('O -ve', 'O -ve'), ('AB +ve', 'AB +ve'), ('AB -ve', 'AB -ve')], help_text='Blood Group', max_length=4),
        ),
        migrations.DeleteModel(
            name='Attendancee',
        ),
    ]
