# Generated by Django 2.2 on 2019-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191125_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Hostage',
            new_name='Resident',
        ),
        migrations.AlterField(
            model_name='profile',
            name='BloodGroup',
            field=models.CharField(blank=True, choices=[('A +ve', 'A +ve'), ('A -ve', 'A -ve'), ('B +ve', 'B +ve'), ('B -ve', 'B -ve'), ('O +ve', 'O +ve'), ('O -ve', 'O -ve'), ('AB +ve', 'AB +ve'), ('AB -ve', 'AB -ve')], help_text='Blood Group', max_length=6),
        ),
    ]
