# Generated by Django 2.2 on 2019-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191204_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Resident',
            field=models.CharField(blank=True, choices=[('DS', 'Day Scholar'), ('HSTL', 'Hostel'), ('PG', 'Paying Guest')], help_text='Resident of', max_length=15),
        ),
    ]
