# Generated by Django 3.0.3 on 2020-04-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20200224_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intassign',
            name='department',
            field=models.CharField(choices=[('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('OTHER', 'OTHERS')], default='MECH', max_length=5),
        ),
        migrations.AlterField(
            model_name='internal',
            name='dept',
            field=models.CharField(choices=[('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('OTHER', 'OTHERS')], default='MECH', max_length=5),
        ),
        migrations.AlterField(
            model_name='semassign',
            name='department',
            field=models.CharField(choices=[('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('OTHER', 'OTHERS')], default='MECH', max_length=5),
        ),
        migrations.AlterField(
            model_name='semester',
            name='dept',
            field=models.CharField(choices=[('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ECE', 'ECE'), ('CSE', 'CSE'), ('OTHER', 'OTHERS')], default='MECH', max_length=5),
        ),
    ]
