# Generated by Django 2.2 on 2019-11-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_semester_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='tcred',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subcred',
            field=models.IntegerField(),
        ),
    ]
