# Generated by Django 2.2 on 2019-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_auto_20191204_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='marksob',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='markstot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
