# Generated by Django 2.2 on 2019-12-04 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('console', '0007_auto_20191204_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='internals',
            new_name='Internal',
        ),
    ]
