# Generated by Django 2.2 on 2019-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_auto_20191204_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internal',
            old_name='marksob',
            new_name='marks1',
        ),
        migrations.AddField(
            model_name='internal',
            name='marks2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internal',
            name='marks3',
            field=models.IntegerField(default=0),
        ),
    ]
