# Generated by Django 2.2 on 2019-12-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_internal_marksob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='semester',
            name='marksob',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='markstot',
        ),
    ]
