# Generated by Django 2.2 on 2019-12-06 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_auto_20191206_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.Grade'),
        ),
    ]
