# Generated by Django 2.2 on 2019-12-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_subjectassign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectAssign',
        ),
    ]
