# Generated by Django 2.2 on 2019-12-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0019_auto_20191206_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semassign',
            name='semester',
        ),
        migrations.AddField(
            model_name='semassign',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.Subject'),
        ),
    ]
