# Generated by Django 2.2 on 2019-12-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0020_auto_20191206_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='result',
            field=models.CharField(choices=[('RA', 'Reappearance is Required'), ('W', 'Withdrawal'), ('SE', 'Sports Exemption'), ('*Ab', 'Absent for Univeristy Exam'), ('PASS', 'PASS')], default='PASS', max_length=30),
        ),
    ]
