# Generated by Django 2.2 on 2019-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0022_auto_20191208_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal',
            name='marks',
            field=models.CharField(blank=True, default=100, max_length=3),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks1',
            field=models.CharField(blank=True, default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks2',
            field=models.CharField(blank=True, default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks3',
            field=models.CharField(blank=True, default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marksob',
            field=models.CharField(blank=True, default=0, max_length=3),
        ),
    ]
