# Generated by Django 2.2 on 2019-12-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0024_auto_20191208_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal',
            name='marks',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marksob',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
