# Generated by Django 2.2 on 2019-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0025_auto_20191208_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal',
            name='marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marksob',
            field=models.IntegerField(default=0),
        ),
    ]
