# Generated by Django 2.2 on 2019-12-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0026_auto_20191208_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal',
            name='marks',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marksob',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='grade',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.Grade'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='result',
            field=models.CharField(blank=True, choices=[('RA', 'Reappearance is Required'), ('W', 'Withdrawal'), ('SE', 'Sports Exemption'), ('*Ab', 'Absent for Univeristy Exam'), ('PASS', 'PASS')], default='PASS', max_length=30, null=True),
        ),
    ]
