# Generated by Django 2.2 on 2019-12-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0027_auto_20191208_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.Grade'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='result',
            field=models.CharField(choices=[('RA', 'Reappearance is Required'), ('W', 'Withdrawal'), ('SE', 'Sports Exemption'), ('*Ab', 'Absent for Univeristy Exam'), ('PASS', 'PASS')], default='PASS', max_length=30),
        ),
    ]
