# Generated by Django 2.2 on 2019-12-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0028_auto_20191208_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.Grade'),
        ),
    ]
