# Generated by Django 2.2 on 2019-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0029_auto_20191208_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='result',
            field=models.CharField(choices=[('PASS', 'PASS'), ('RA', 'Reappearance is Required'), ('W', 'Withdrawal'), ('SE', 'Sports Exemption'), ('*Ab', 'Absent for Univeristy Exam')], default='PASS', max_length=30),
        ),
    ]
