# Generated by Django 2.2 on 2019-12-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0030_auto_20191208_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='semassign',
            name='department',
            field=models.CharField(choices=[('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('EEE', 'Electrical and Electronics'), ('ECE', 'Electronics and Communication'), ('CSE', 'Computer Science and Engineering'), ('OTHER', 'Others')], default='MECH', max_length=5),
        ),
        migrations.AddField(
            model_name='subjectassign',
            name='department',
            field=models.CharField(choices=[('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('EEE', 'Electrical and Electronics'), ('ECE', 'Electronics and Communication'), ('CSE', 'Computer Science and Engineering'), ('OTHER', 'Others')], default='MECH', max_length=5),
        ),
    ]
