# Generated by Django 2.2 on 2019-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0033_internal_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='dept',
            field=models.CharField(choices=[('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('EEE', 'Electrical and Electronics'), ('ECE', 'Electronics and Communication'), ('CSE', 'Computer Science and Engineering'), ('OTHER', 'Others')], default='MECH', max_length=5),
        ),
    ]
