# Generated by Django 2.2 on 2020-01-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0034_semester_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internal',
            name='marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marks3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internal',
            name='marksob',
            field=models.IntegerField(default=0),
        ),
    ]
