# Generated by Django 2.2 on 2020-01-21 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0035_auto_20200121_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intassign',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intassign',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.Subject'),
        ),
        migrations.AlterField(
            model_name='internal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internal',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.Subject'),
        ),
        migrations.AlterField(
            model_name='semassign',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='console.Subject'),
        ),
        migrations.AlterField(
            model_name='semassign',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semester',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='console.Grade'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semester',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.Subject'),
        ),
    ]
